version: '3.3'
services:
  db:
    container_name: db
    image: mysql:8
    environment:
      MYSQL_DATABASE: edp
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: 1
    ports:
      - 3306:3306
  web:
    image: edp-server:1
    ports:
      - 8090:8090
    depends_on:
      - db